server:
    port: 3000

cron:
    spec: '*/5 * * * * *'

database:
    engine: 'mysql'
    host: 'localhost'
    name: 'monkeys'
    password: 'poop'
    user: 'mark'

redis:
    host: 'red1.db'
    port: 6379
